demoSlicerData = [
    Slicer2,
    Slicer1,
    Slicer3,
    Slicer4,
    Slicer5,
    UCLA_1131,
    UCLA_1189,
//    UCLA_1337,
//    UCLA_1404,
//    UCLA_1491,
////    MRHead,
////    Daniel,
    LeftHemi,
////    RightHemi,
////    Car,
////    Points,
//    PartialFibers,
////    WholeFibers,
]